### ISSUE TITLE
Vendor prefixing

### ISSUE THREAD

**Issue by liegeandlief** [wix/stylable#1024]
Hi there, and thanks for the amazing project! Please can you let me know whether Stylable automatically adds vendor prefixes when generating CSS? If not is this something you could support, possibly by reading the Browserslist config from `.browserslistrc` or from the `browserslist` property in `package.json`, in order to determine which prefixes to add. Thanks :)

**Comment by tomrav** [comment]
You can take a look [here](https://github.com/wix/stylable/blob/master/packages/webpack-plugin/test/e2e/projects/autoprefixer-project/webpack.config.js#L15) to see an example of the postcss auto-prefixer plugin being used with Stylable.

**Comment by liegeandlief** [comment]
That's great, thanks for replying so quickly!

**Comment by tomrav** [comment]
Glad I could help. :)
