### ISSUE TITLE
Warning when using @st-scope with tag selectors or :global()

### ISSUE THREAD

**Issue by alisey** [wix/stylable#1048]
The following warnings appear in the console during compilation, and they are also shown by stylable intelligence:

```
WARNING in Stylable: "@st-scope" must receive a simple selector, but instead got: ":global(.foo)"
@st-scope :global(.foo) { }
```

```
WARNING in Stylable: "@st-scope" received an unknown symbol: "html"
@st-scope html { }
```

The compiled CSS works correctly, though.

**Comment by barak007** [comment]
In theory @st-scope is working with any selector. we wanted to limit it to locals only but we can start thinking about open it.

**Comment by alisey** [comment]
I don't have a pressing need for this. It's just that the behavior doesn't match [documentation](https://stylable.io/docs/references/st-scope):

> The scoping directive receives a single simple selector (Tag selector, Class selector or Component root) to use for its scoping.

Maybe we should simply remove 'tag selector' from there, and clarify the use with class names, like not being able to use classes from a different file or `:global()`.

And also remove the words `simple selector`, because that's something else entirely:
> A simple selector is either a type selector or universal selector followed immediately by zero or more attribute selectors, ID selectors, or pseudo-classes, in any order.

(Source: https://www.w3.org/TR/CSS22/selector.html)

@tomrav wdyt?

**Comment by tomrav** [comment]
If only we had nesting support...

Our docs should be updated, I was not aware of that official W3C definition for a simple selector.

As for extending `@st-scope`, we could extend it to support any selector, or any selector within `:global` at a minimum. I'm not sure I see a downside to going with the former approach, except it being more work to implement.

**Comment by idoros** [comment]
working now. as suggested `@st-scope` now accepts any selector.
