### ISSUE TITLE
Make it an error in JS to use classes not defined in stylesheet

### ISSUE THREAD

**Issue by alisey** [wix/stylable#1050]
```ts
import { classes } from './style.st.css';

classes.iDontExist; // No type or runtime error, TypeScript thinks it's a string
```

Making a typo in the class name or renaming/deleting the class in the stylesheet without updating the JS file is a pretty common error that is not caught right now.

The lack of error reporting also might be making developers reluctant to delete potentially unused classes from stylesheets, because it's hard to check if they are still in use.

If it's too much work to make this a type error, let's at least make it a runtime error. Should be easy enough with proxies.

`StylableDOMUtil.scopeSelector('.root')` is another place where error checking would be valuable.

**Comment by barak007** [comment]
It will be nice. maybe we can use Proxy to detect it in dev mode.

**Comment by idoros** [comment]
this gets a bit better with #1766
