### ISSUE TITLE
change in theme needs a 'yarn start' to take affect :(

### ISSUE THREAD

**Issue by DeDuckProject** [wix/stylable#110]
running on mac with
```json
"stylable": "4.0.10",
"stylable-integration": "5.1.0",
```

changes in theme don't take place unless I kill node and run it again.
@barak007 If you need my exact setup let me know 💃🏼

**Comment by idoros** [comment]
fixing this issue in `stylable-integration`

**Comment by idoros** [comment]
@DeDuckProject - can you confirm fix?

**Comment by DeDuckProject** [comment]
fixed
