### ISSUE TITLE
Strange behaviour when component has a displayName

### ISSUE THREAD

**Issue by liegeandlief** [wix/stylable#1252]
Hi there. I am seeing some strange behaviour when building on my CI server where the classes produced by Stylable are sometimes correct and sometimes not, resulting in the styling of my application sometimes being broken. Strangely removing the display name property from a particular component seems to fix this.

e.g. I have a component called DataTable which has the following display name `DataTable.displayName = 'DataTable'`. The Stylable stylesheet for this component also contains the namespace declaration `@namespace "DataTable";`. When these are both present the issues presents intermitently when building on CI. But when I remove the display name from the component this issues goes away.

I am using Stylable 3.7.2 and version 3.7.2 of the webpack plugin also.

Apologies for not being able to provide more information, I am not exactly sure what would be useful as I don't understand the internal workings of Stylable very well.

But it does seem to me to have to do with the display name. Does Stylable make use of the display name internally?

**Comment by tomrav** [comment]
First off, I salute you for being on the latest version. As for your question, we do not access or use `displayName` internally in any way.

Does the process you describe on the CI involve SSR rendering? my immediate suspicion is some sort of namespace collision.
Are you able to reproduce this locally somehow?

**Comment by liegeandlief** [comment]
Unfortunately it never seems to happen when I build locally. There is no SSR it is just a webpack build on a single entrypoint. The application does use dynamic imports for code splitting.

All my CI server does is run `npm ci && npm run build` and then uploads the produced files to S3.

My webpack config for the Stylable webpack plugin is as follows:

```
  const stylableWebpackPlugin = new StylableWebpackPlugin({
    filename: `./bundles/stylable/[name].[hash].css`,
    transformHooks: {
      postProcessor: stylableResult => {
        postcss([autoprefixer]).process(stylableResult.meta.outputAst).sync()
        return stylableResult
      }
    }
  })
```

Stylable is the last webpack plugin to be applied after: HtmlWebpackPlugin, MiniCssExtractPlugin, MomentLocalesPlugin and MomentTimezoneDataPlugin.

I also apply the following optimisations in my webpack config:

```
    optimization: {
      splitChunks: {
        chunks: 'all'
      },
      runtimeChunk: 'single'
    }
```

**Comment by tomrav** [comment]
Can you share more about what the actual result in the broken cases is? Are the styles there but not properly ordered or namespaced? Are some styles just missing?

Is this something I can look at to attempt and debug? If not can you perhaps share a minimal reproduction?

**Comment by AviVahl** [comment]
Is stylable outputing a single .css file in your setup? If it is, might be useful to grab the generated asset from S3 and compare that to the one generated when building locally. If we find differences, they might assist pointing us in the right direction.

**Comment by liegeandlief** [comment]
I've actually done a few more builds on CI and I'm now not sure that it is related to display names. The issue seems to happen sporadically even when nothing has changed. I have attached two CSS files. One when the styles look okay (good.txt) and another when they don't (bad.txt).
[bad.txt](https://github.com/wix/stylable/files/4884964/bad.txt)
[good.txt](https://github.com/wix/stylable/files/4884965/good.txt)

**Comment by liegeandlief** [comment]
The build does produce other stylesheets but I have done a comparison of the other stylesheeets and they are identical. These are the only two which differ.

**Comment by tomrav** [comment]
We are seeing some differences between the two CSS files you provided. Some of our optimizations seems to have occurred at different times in the two builds leading to different namespacing. However, if the entire project is built in one go, and there are no additional processes taking place, then the JS should be synced to the namespaces generated in that build.

We're still missing information to make a qualified guess as to what doesn't exactly match. 

- Is it possible some of the files you are serving are cached, or not provided as part of the same build process?
- Could something with the deployment have you serve older files, or something (like the JS) is cached that way?
- Can you provide the JS that was generated for the two builds? 
- If you can actually locate a broken piece of DOM and share what actual/expected values for it, then that could help as well.

Possible workaround that may assure that this is the issue we think it is, would be to disable the namespace optimizations that we perform. You can do this by adding the following to your Stylable webpack config. Granted this is not a long term solution. Also, please try turning on the `skipDynamicCSSEmit` option - this will prevent unused dynamic files from being emitted (this will be `true` by default soon, and might make your debugging a bit cleaner). 
```css
new StylableWebpackPlugin({
  skipDynamicCSSEmit: true
  optimize: {
    shortNamespaces: false
  }
}),
```

**Comment by liegeandlief** [comment]
I made those suggested changes and have run six consecutive builds on CI without the issue occurring so it does indeed seem to have fixed it.

Regarding your points all the files are generated during the single webpack build process. Once the build finishes then the S3 bucket from which they are served is emptied and the new files uploaded to it.

There is no caching of files occurring on the server side. Caching response headers are added when the files are requested but I have tested after clearing the browser cache and this does not fix the issue.

The build uses webpack chunk splitting so it generates many JS files for a single page (about 10 files) which are all minified. If you still think they may be useful then I can send them across.

I will take a look to try and identify some broken DOM and let you know.

Thanks!

**Comment by tomrav** [comment]
Glad at least the work-around worked, but I'd like to try and figure it out still.

If you can share those "broken" JS files maybe we could find a hint there.

**Comment by liegeandlief** [comment]
A bit more context...

I currently don't use stylable across the whole application. Certain parts of it are styled by other means. But on the page I am seeing the issue I render one main component and it and all of its children are styled using stylable only. The component returns the following:

```
    <ContentWrapper loading={isLoading}>
      <PageHeading text={lang.data['page-titles__users']} withLoadingIndicator loading={isLoading} />

      <section className={classes.contentPanel}>
        <section className={classes.controlBar}>
          <Button
            disabled={isLoading}
            className={classes.inviteUserButton}
            large
            light
            shadow
            onClick={onInviteUserButtonInteract}
            onKeyPress={onInviteUserButtonInteract}
          >
            <IconAdd
              aria-label={lang.data['purchase-details__item-ticket-not-gifted-icon-label']}
              title={lang.data['purchase-details__item-ticket-not-gifted-icon-label']}
              className={classes.inviteUserButtonIcon}
            />
            {lang.data['users__button-label-invite-user']}
          </Button>
        </section>

        <DataTable
          columns={tableColumns}
          data={tableData}
          loading={isLoading}
          sortCol={tableSortBy}
          sortDir={tableSortDir}
          onSort={handleTableOnSort}
        />
        <Pagination links={paginationLinks} onInteract={handlePagination} />

        <ModalDialog
          isOpen={state.showInviteUserUI}
          onCloseButtonInteract={onModalCloseButtonInteract}
          className={classes.modalDialog}
          contentLabel={lang.data['users__modal-label-invite-users']}
        >
          <InviteUser
            onSuccess={handleInviteUserSuccess}
            onError={handleInviteUserError}
          />
        </ModalDialog>
      </section>
    </ContentWrapper>
```

The styable CSS for this component is as follows:

```
@namespace "Users";

:import {
  -st-from: "../../../styles/theme.st.css";
  -st-named: paddingBase, marginBase;
}

:import {
  -st-from: '../../primitives/ModalDialog/index.st.css';
  -st-default: ModalDialog;
}

:import {
  -st-from: '../../primitives/Button/index.st.css';
  -st-default: Button;
}

:import {
  -st-from: '../../primitives/CustomSvgIcon/index.st.css';
  -st-default: CustomSvgIcon;
}

.contentPanel {
  padding: 0 value(paddingBase);
}

.controlBar {
  margin-bottom: calc(value(marginBase) * 2);
  display: flex;
}

.inviteUserButton {
   -st-extends: Button;  
  margin-left: auto;
  padding: 0 value(paddingBase);  
}

.inviteUserButtonIcon {
  -st-extends: CustomSvgIcon;
  margin-right: calc(value(marginBase) / 2);
  margin-left: calc(0px - value(marginBase) / 3);  
}

.modalDialog {
   -st-extends: ModalDialog;
}

.modalDialog::dialog {
  width: 550px;
}
```

When the issue occurs the `section` with the class `contentPanel` has the class `s134` but this class does not appear anywhere in the generated CSS. The styles expected for `s134` are actually present in the generated CSS under the class `s135`.

Unfortunately it turns out I am actually not able to share final JS bundles due to company policy.
