### ISSUE TITLE
Add ability to use contenthash in file names

### ISSUE THREAD

**Issue by liegeandlief** [wix/stylable#1253]
Currently my webpack setup contains the following:

```
  const stylableWebpackPlugin = new StylableWebpackPlugin({
    filename: `./bundles/stylable/[name].[hash].css`,
  })
```

The problem with this is that the hash in the filename varies on each build even when the emitted file has the same content. This means that clients can't cache optimally.

In other parts of my webpack config I am able to use `[contenthash]` instead of `[hash]`. This bases the hash on the file contents so if it doesn't change then it will be the same hash between builds.

When I try and use `[contenthash]` with stylable I get the following error: `Path variable [contenthash] not implemented in this context: ./bundles/stylable/[name].[contenthash].hashedUnique.css`

I would like to propose adding thie functionality as I feel it would be a useful addition.

**Comment by tomrav** [comment]
This is resolved in our [latest version](https://github.com/wix/stylable/releases/tag/v3.8.0).
