### ISSUE TITLE
Support named import of @keyframes declaration

### ISSUE THREAD

**Issue by PeterShershov** [wix/stylable#1271]
Allow importing `@keyframes` as named imports from different files

### spinner.st.css
```
@keyframes spin {
    100% {
        transform: value(rotate);
    }
}
```
### other-spinner.st.css
```
-st-import {
    -st-from: '../../my-file.st.css';
    -st-named: spin;
}

.myClass {
    animation: spin 2s linear infinite;
}
```

**Comment by tomrav** [comment]
Having discussed this issue internally we've come away with the following conclusions:
- seeing as we scope the name of keyframes, we definitely want to provide the ability to import and export them
- once we allow such imports, we run across the problem of keyframes and classes/vars sharing the same namespace in stylesheet imports
- our suggested solution is to import keyframes using a specific utility function inside the `-st-named` property

```css
:import {
  -st-import: './index.st.css';
  -st-named: somePart, someVar, keyframes(someKeyframe); 
}
```

In the future, we can expand this format to support additional type imports  (e.g. classes, elements, vars and css vars) for a more explicit importing experience.

In addition, our upcoming import shorthand (`@import [someClass, keyframes(someKeyframe)] from './index.st.css';`) should also play nice with the suggested syntax.
