### ISSUE TITLE
Problem using `st-extends` NOT on root element 

### ISSUE THREAD

**Issue by JoMarton** [wix/stylable#150]
This is my use case:
```render() {
   return ( case ? <AAA className="aaa"/> : <BBB className="bbb"/>)
}
```

I want `bbb` class to extend another stylesheet but not `aaa`. 

when I do:
```.root{-st-extends: LALA}``` it works but also extends AAA. 
```.bbb{ -st-extends: LALA}``` it doesn't work

**Comment by tomrav** [comment]
@JoMarton Can you please clarify this with a bit more extra details on your components setup and use case?
