### ISSUE TITLE
Multiple components exported from the same file do not inherit styles properly

### ISSUE THREAD

**Issue by Zombiefruit** [wix/stylable#1628]
Demo: https://zombiefruit-stylable-issue-demo-2q4w.github.dev/

We have:

- `header.tsx`: exports `Header` and `BlueHeader`. All `BlueHeader` does is render `Header` and add a style to it.
- `header.st.css`: used by the `Header` component.
- `blue-header.st.css`: used by the `BlueHeader` component. The `root` of this stylesheet extends `header.st.css`.

The `BlueHeader` component attempts to override the `background-color: red` styling of `Header`, but does not.

**Comment by barak007** [comment]
First of all it seems that the `BlueHeader` tries to set the header to be `blue` and not `red` and all seems to work fine for me.
What am I missing?

**Comment by barak007** [comment]
By the way.... I had to clone the repo from: https://github.com/Zombiefruit/stylable-issue-demo

The codespace didn't work for me

**Comment by Zombiefruit** [comment]
Whoa whoa whoa. It was red before, but I cloned locally and installed and it's blue now. Really not sure what's going on.

**Comment by tomrav** [comment]
Closing as not reproduced, please re-open if come across the issue again.
