### ISSUE TITLE
Stylable@4 browser code requires a polyfill for the node js module `path`

### ISSUE THREAD

**Issue by bodia-uz** [wix/stylable#1757]
Inside the browser code of stylable@4, there is a [package](https://www.npmjs.com/package/enhanced-resolve) that uses node js module [`path`](https://nodejs.org/api/path.html). 

So to use stylable@4, the polyfill of the [`path`](https://nodejs.org/api/path.html) is required.

**Comment by barak007** [comment]
We know that you currently need to add two polyfills one for `os` and the other for `path` . 
The `os` polyfill will not be required soon but the `path` one is in use and will remain required.
