### ISSUE TITLE
rule node doesn't get source object when returning diagnostics

### ISSUE THREAD

**Issue by qballer** [wix/stylable#178]
This happens specially when running diagnostics on custom selectors.
Reconstruct bug: 

1. Install Stylable Intelligence
2. type `@custom-selector: --l` 
3. You will notice that the diagnostic appears in location (0,0). this a defence mechanism against this bug. It only happens when there is no source node. originating custom selector source node should be in the node. 

You can check it out here https://github.com/wix/stylable/blob/master/src/stylable-processor.ts#L272 in the `handleCustomSelectors` function.

**Comment by tomrav** [comment]
Resolved.
