### ISSUE TITLE
vars used in `:global(selector) {}` arent redefined by theme 

### ISSUE THREAD

**Issue by tyv** [wix/stylable#179]
here https://github.com/tyv/do-some-bit/blob/master/src/components/list/list.st.css

`mainBackgroundColor` resolved to 2 different values.
in first case it is yellow as redefined here: https://github.com/tyv/do-some-bit/blob/master/src/themes/fancy.st.css#L7

and in global this is https://github.com/tyv/do-some-bit/blob/master/src/project.st.css#L5

**Comment by tomrav** [comment]
An additional selector override should be created whenever a global class is used in conjunction with a theme override. Will add an example shortly.
