### ISSUE TITLE
Tests are stuck idle, never closing, on Mac CI

### ISSUE THREAD

**Issue by AviVahl** [wix/stylable#1808]
Not sure when it started, but on the Mac containers tests sometimes get stuck.

I suspect the `rollup` changes, or more specifically- watch tests. on Mac, `chokidar` usually uses `fsevents`. this is a point where the platforms differ. AFAIK, `rollup` inlines a copy of `chokidar` inside its package.

**Comment by idoros** [comment]
I had 2 macOS jobs not initiating for over 25min before starting and finishing ok (see [this run](https://github.com/wix/stylable/runs/2608637685?check_suite_focus=true) which took 37min although none of the runs took more the 10min). I think they are just stuck in some queue waiting for a machine.

**Comment by AviVahl** [comment]
Example run: https://github.com/wix/stylable/runs/2610498398

**Comment by tomrav** [comment]
I think this was resolved as I haven't experienced this in a while. Closing.
