### ISSUE TITLE
cannot use imported variables in local variables;

### ISSUE THREAD

**Issue by VKobeliatsky** [wix/stylable#183]
project.st.css
```css
:vars {
  myBorderStyle: solid;
  myBorderColor: red;
}
```
local.st.css
```
:import {
  -st-from: './project.st.css';
  -st-named: myBorderStyle, myBorderColor;
}

:vars {
  myBorder: value(myBorderStyle) 2px value(myBorderColor);
}

.root {
  border: value(myBorder);
}
```
STR
1) apply `local.st.css` to a component;

ER: the element has a solid red border 2px wide;
AR: the element has no border, only `border: red` property is set;

@LeonidLevi

**Comment by tomrav** [comment]
Resolved in v5.1.0 
https://github.com/wix/stylable/releases/tag/v5.1.0
