### ISSUE TITLE
"createModuleSource" in module-utils needs breaking up

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#1843]
Over time this piece of code has grown to support more and more cases, it might be time to simplify it's options and break it up.

Current signature:
```ts
export function createModuleSource(
    stylableResult: StylableResults,
    moduleFormat = 'cjs',
    includeCSSInJS: boolean,
    moduleId = JSON.stringify(stylableResult.meta.namespace),
    renderableOnly = false,
    depth: string | number = '-1',
    staticRequests: string[] = [],
    runtimeRequest = '@stylable/runtime',
    afterModule: string[] = [],
    dtsContent?: string
)
```

**Comment by idoros** [comment]
I think the different functions could be exported for each module type before next major, and the main `createModuleSource` can be deprecated and removed in next major

**Comment by tomrav** [comment]
Looked at this, doesn't seem like there's much to do here.
