### ISSUE TITLE
CLI should have no output module type defined by default

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#1854]
Currently when running `stc` the only module type that defaults to true is `cjs`. While this can fit some use-cases, it definitely doesn't fit all of them.

In the next major version, we can break this behavior and force the user to specify all module types they require.

Something like:
```sh
stc --modules="cjs, stcss, dts, dtsSourceMap"
```

**Comment by tzachbon** [comment]
Fixed in #2441, and will be released in Stylable version 5
