### ISSUE TITLE
React + Storybook + wix-style-react

### ISSUE THREAD

**Issue by okansahin** [wix/stylable#1903]
Hello,

I'm trying to create new project with react(create-react-app) and storybook and wix-style-react.

In storybook's main.js i configured webpack for stylable,

```
webpackFinal: (config) => {
  applyWebpackConfigStylableExcludes(config);

  config.plugins.push(new StylableWebpackPlugin());
  return config;
}

```

and I'm getting
`ERR! TypeError: Cannot read property 'dependencies' of undefined` after run yarn storybook.

When I try to start react project with yarn start,
I get

`TypeError: Cannot read property 'Spacing' of undefined
Module../node_modules/wix-style-react/dist/es/src/Box/constants.js
node_modules/wix-style-react/dist/es/src/Box/constants.js:19`

I just want to use wix-style-react and storybook in my react project, i have no idea is that necessary to add stylable to project. Is my way correct?

Thank you.

**Comment by AviVahl** [comment]
`create-react-app` currently uses webpack v4.
This means you'll have to use the previous major of stylable (v3) to support it. 
stylable v4 supports webpack v5 and above.

In addition, `create-react-app` doesn't allow us to modify the config (AFAIK), so you may have to eject if you wanna add stylable support to `react-scripts` related commands.

**Comment by okansahin** [comment]
Thank you for information @AviVahl 

I cloned stylable#3.x and created a project with create-stylable-app but it still installs the new version of depencies. 

As a new way I added stylable v3 to a project created with create-react-app and override create-react-app's webpack.config with [react-app-rewired](https://www.npmjs.com/package/react-app-rewired) and [webpack-merge](https://www.npmjs.com/package/webpack-merge) but there is so many version conflicts occurred with webpack loader depencies.

Somehow I set these as well, but in the end I got errors in some files of wix-react-style es files because of babel-loader. Maybe it can be solved with more effort, but for me time was more important and I decided to continue without create-react-app.

Maybe this is not the subject of this repo, but I want to ask because it is under the same organization. Surely there will be people who come here wondering the same thing.

Is wix-style-react restricted for public usage? The repo is unreachable and the last version on npm is 9.116 but in the doc it is 9.133. Do you think using this module will cause trouble for us in the future?

Thank you for your valuable time.

**Comment by AviVahl** [comment]
Just to clarify:
`create-stylable-app` already uses `webpack@5` and will only work with `stylable@4+`.

`create-react-app` still uses `webpack@4` and will only work with `stylable@3`. using `react-app-rewired` might not be enough, as one needs to both add the `@stylable/webpack-plugin` AND tell the other style loaders to exclude `.st.css` files from being processed. The only way I know to make that fully happen is to eject.

`wix-style-react` has become a private repository for internal usage. I'm unsure whether new open source versions will be released in the future, but I wouldn't bet on it. Using it in a new project might prove to be problematic if that's indeed the case. Perhaps @shlomitc can clarify.

**Comment by shlomitc** [comment]
`wix-style-react` code base is not public, but the built code will keep being published to `npmjs` and the docs will stay public. New versions aren't currently published since we're still working on our publishing tools, but this will work again soon and new versions will be published.

The library is already very mature and stable so I feel comfortable recommending using it for any public project.

**Comment by AviVahl** [comment]
Thanks for clarifying. :+1: 
Is there a place where someone using the public version can report issues and/or ask for help?

**Comment by shlomitc** [comment]
We’ll create a public repo that showcases the libraries usage which could also be a good place to post issues. I’ll update this thread when this will happen

**Comment by tomrav** [comment]
Closing as it looks like this was cleared up, feel free to open another if something comes up.

**Comment by shlomitc** [comment]
As promised, we created a repo explaining how to integrate our components libraries. Currently it covers `wix-style-react` with both `create-stylable-app` and a clean `webpack` creation. Anyway, they're both very similar.

Once `wix-style-react` will become 100% stylable (we're not that far), the configuration can be reduced even more
https://github.com/wix-incubator/design-systems-examples
