### ISSUE TITLE
:global selector ignores commas

### ISSUE THREAD

**Issue by idoros** [wix/stylable#1906]
placing commas in `:global` selector doesn't produce any warnings and removes it during transform.

```css
:global(a, b) {}

/*transforms to*/

a b {}
```
[playground example](https://wixplosives.github.io/stylable-playground/#state=%28%27files%21%28*%21%21global%257Ba%252C%2520b%257D%2520%28-%2520%2520%2520%2520-%29--%27%29%7Eselected%21*%27%29*%27%252Findex.st.css-%255Cn%2501-*_)

I think expected behavior should be to produce an error and don't transform the `:global` at all.

--- edit ---

`:global(a, b)` transforms the selector as is and omits the `,` resulting in an unintended selector transformation. The issue is that a merging-in the internal complex selector can be transformed in more then one way. For example `.a :global(.b, .c) .d` can be transformed to `.a .b, .c .d` or `.a .b .d, .a .c .d`, since there is no one correct answer, complex selectors should not be transformed and report a `complex selector is not supported in :global`.

**Comment by tomrav** [comment]
Another option would be to create the required permutations for all cases `a, b {}`

**Comment by idoros** [comment]
Thought about this, but something like:
```css
.x :global(a, b) .y {}
/*-->*/
.x a, b .y {}
```
This feels like a mistake. the initial parsing, done by a computer or a human, assumes a single selector, and the transformation break it into 2.

**Comment by tomrav** [comment]
Maybe it should transpile it to the following?

```css
.x a .y,
.x b .y {}

```

**Comment by idoros** [comment]
I think that is a bit confusing. splitting the selector like this is hard to explain and is not very predictable. 
Supporting a single complex selector is good enough in my opinion.

I would add a warning and an error in a next major.

btw, css-modules has the exact behavior (dropping the comma).

**Comment by idoros** [comment]
related to #310
