### ISSUE TITLE
When import is not accessed, the 'Imported file not found' diagnostic is not shown

### ISSUE THREAD

**Issue by tempit** [wix/stylable#193]
:import {
    -st-from: './imporxt.st.css';
    -st-default: Comp;
}

.local {
    -st-extends: Com;
}

Shows: cannot resolve \"-st-extends\" type for \"Com\"
But does not show error that imporxt.st.css does not exist.

**Comment by tomrav** [comment]
It should also discern between missing files, and missing symbols.
