### ISSUE TITLE
Serve stylable.io over HTTPS

### ISSUE THREAD

**Issue by fvsch** [wix/stylable#194]
Not critical, but I try to share HTTPS links only. Maybe that's just snobbery :P

(Also I use an extension which tries the HTTPS version first, before falling back on HTTP if it fails, so it makes HTTP sites load more slowly.)

**Comment by idoros** [comment]
That sounds reasonable. I will take a look at how to serve a gh-page from custom url on https and fix.

**Comment by idoros** [comment]
@fvsch - done
