### ISSUE TITLE
@property definition override conflicting imported symbol

### ISSUE THREAD

**Issue by barak007** [wix/stylable#1955]
### Actual Behavior

[Playground Link](wixplosives.github.io/stylable-playground/#state=%28%27files%21%282%21%27%2540st-import%2520%255B7%255D%2520from%2520%255C%27.3%255C%275*%2540property%252075*6*%2520%2520%2520%25204red5%29%27%7E3%21%2764green8.label18.icon18%27%29%7Eselected%212%278%255Cn0.st.css1%2520%282%27%252Findex03%252Fbutton047%253A%25205%253B*6.root17--x8%29*%2501876543210*_)

### Expected Behavior

We should not allow to redeclare imported css vars 

### Version

@stylable/core@4.5.0

**Comment by tzachbon** [comment]
When we used the old import syntax it gets a warning. [Playground link](https://wixplosives.github.io/stylable-playground/#state=%28%27files%21%284%21%21import3Bfrom2%255C%27.5%255C%27%253BBnamed296A*%2540property%252096*80-x2red6%29%27%7E5%21%27892greenA.label3A.icon3A%27%29%7Eselected%214%27A%255Cn0*77-1.st.css2%253A%25203%2520%284%27%252Findex15%252Fbutton16%253B*7%2520%25208.root39--xA%29*B0st-%2501BA9876543210*_)
