### ISSUE TITLE
Stylesheet helper doesn't transform non-root classes

### ISSUE THREAD

**Issue by adriantoine** [wix/stylable#200]
Hello!

I ran a quick test and I don't know if I am doing something wrong or if this is a bug. I tried to use this library without the `stylable` helper from `wix-react-tools`, here is the content of `style.st.css`:

```css
.menu {
  color: red;
}
```

and here is the content of my component:

```jsx
import React from 'react';
import style from './style.st.css';

const Menu = () => (
  <div {...style('')}>
    <div {...style('menu')}>Hello World</div>
  </div>
);

export default Menu;
```

and I end up with this markup:

```html
<div class="menu2582437757💠root">
  <div class="menu2582437757💠root menu">Hello World</div>
</div>
```

so the `menu` class name hasn't been transformed and the `root` class name has been added to the child, I would expect something like:

```html
<div class="menu2582437757💠root">
  <div class="menu2582437757💠menu">Hello World</div>
</div>
```

I could unwrap the div and have `menu` as the root but according to the [React integration](https://stylable.io/docs/getting-started/react-integration), it should work.

Am I doing something wrong or did I misunderstand something?

**Comment by adriantoine** [comment]
I did a small repo which reproduces this behavior: https://github.com/adriantoine/stylable-class-bug, let me know if it's an expected behavior, in which case, how do I get only the `menu` class with the states available?

**Comment by adriantoine** [comment]
Thanks for [your answer](https://github.com/adriantoine/stylable-class-bug/pull/1), it works now, I guess I got confused about what `style('menu')`.

**Comment by barak007** [comment]
Thanks for testing Stylable.

Right now the stylesheet function only works for the root node of your component. 
It's a bug, the root className should be added only when you provide props to the stylesheet function.

**Comment by adriantoine** [comment]
Ok, thanks for your help, it works for now.

So yeah I've notices that

```js
style(style.menu)
```

Returns the `root` class as well, so if you're using the `stylesheet` helper, all classes will get the `root` class which is not what I would expect.

I will reopen this bug if you don't mind.

**Comment by barak007** [comment]
Thank you. 
I already opened it https://github.com/wix/stylable/issues/201, and soon it will be merged.
