### ISSUE TITLE
Declare custom global property with `st-global` function

### ISSUE THREAD

**Issue by tzachbon** [wix/stylable#2009]
### Proposal Description

Today we declare custom global property only with `@st-global-custom-property my-property;` which is pretty robust.
I guess declaring it with `stGlobal` like this `@property stGlobal(my-property)` would be nice.

Prons:
* Unified API - We use this syntax already in `@keyframes`.
* You can declare global and scope properties in the same line - `@property stGlobal(x), y;`
* Close to the native syntax.
* Pretty short
* Declare global CSS vars inside rules / declarations.

**Comment by idoros** [comment]
I would like to align this with keyframes, but I prefer keeping it closer to native declaration with a single property per definition

**Comment by tzachbon** [comment]
> I would like to align this with keyframes, but I prefer keeping it closer to native declaration with a single property per definition 

It seems that we give the ability to declare multiple global symbols in the same line.

**Comment by idoros** [comment]
Under our custom `@st-global-custom-property` or somewhere else?

**Comment by tzachbon** [comment]
> Under our custom `@st-global-custom-property` or somewhere else? 

In the global custom property.

https://stylable.io/docs/references/css-vars#using-global-css-variables

**Comment by barak007** [comment]
I like the idea to expand the use of `stGlobal`.
I also think that defining multiple vars in the native `@property` would require more work, definition and explanations and can be added in later stage so I would wait with that.

for usage/define a global var inside declaration 
```css
 .x {
  stGlobal(--x): var(stGlobal(--y)); ?
  stGlobal(--x): stGlobal(var(--y)); ?
}
```
I'm not sure how pretty is this but I can see something like that working. 
Maybe they don't have to be implemented together.

**Comment by tzachbon** [comment]
> I like the idea to expand the use of `stGlobal`.
> I also think that defining multiple vars in the native `@property` would require more work, definition and explanations and can be added in later stage so I would wait with that.
> 
> for usage/define a global var inside declaration
> 
> ```css
>  .x {
>   stGlobal(--x): var(stGlobal(--y)); ?
>   stGlobal(--x): stGlobal(var(--y)); ?
> }
> ```
> 
> I'm not sure how pretty is this but I can see something like that working.
> Maybe they don't have to be implemented together.

I guess that the value part should be in a different discussion. 
But I totally agree with the property declaration, it would be very nice.

**Comment by tomrav** [comment]
I'm on the fence about the declaration property being a function. Are there any established examples for syntax of this type?

Also, if we're moving to our hyphen notion, then this would become `-st-global(...)` which conflicts with our existing directive. Need to think this through.
