### ISSUE TITLE
native pseudo-classes give a warning in diagnostics 

### ISSUE THREAD

**Issue by arnonkehat** [wix/stylable#222]
diagnostics is not working properly on native pseudo classes.

take a look at the image below. the native `:hover` pseudo-state is giving a warning that it's an unknown state.

![image](https://user-images.githubusercontent.com/8819912/34077590-2307112e-e310-11e7-810b-5d1f15a304a5.png)

**Comment by tempit** [comment]
@barak007 @idoros - There's a list of reserved CSS states in the intelligence code for exactly this reason. Should be copied to stylable and used to filter out diagnostics.

**Comment by tomrav** [comment]
Resolved.
