### ISSUE TITLE
Exposing Stylable internal file system

### ISSUE THREAD

**Issue by tzachbon** [wix/stylable#2236]
### Proposal Description

Today we are not exposing the file system passed to the Stylable instance.

One of the problems is when an API needs a Stylable instance and fs instance, and the user does not provide the same fs instance used inside Stylable, it could lead to unexpected behaviors. 
Regardless this causes a lot of places to expose both the Stylable instance and the fs instance. 
Therefore a lot of code duplications are formed. 

If we would like to solve this issue, today's problem is mainly types mismatch and what type of `fs` to expose. 
I think that creating a generic type that extends the current minimal-fs type.

### Additional Context

Example for providing the fs, and Stylable instance separately.
https://github.com/wix/stylable/blob/master/packages/language-service/src/lib/service.ts#L49

**Comment by AviVahl** [comment]
Above seems like an odd reason to make the entire API generic and expose the original fs type via stylable.

**Comment by tzachbon** [comment]
> Above seems like an odd reason to make the entire API generic and expose the original fs type via stylable.

@AviVahl  Answering a proposal as an "odd" reason without giving arguments that reinforce what you are saying is an odd thing.

**Comment by AviVahl** [comment]
Alright, I'll bite. My other abstraction needs the `fs.someSpecialFn`. Now I would need to specify it as a generic requirement on the Stylable instance type. Meaning, my LanguageService abstraction recieves a `Stylable<SpecialFileSystem>` (which has someSpecialFn). A Stylable instance containing the minimal fs **it acutally needs and uses** isn't enough. If our aim was to separate abstractions using the partial fs api on Stylable itself, this proposal does exactly the opposite.

**Comment by tzachbon** [comment]
Closed until we understand if we want to decouple the entire "file system" from Stylable core and its implications of this process.
