### ISSUE TITLE
CSS Mixin within a CSS Mixin will not transpile correctly

### ISSUE THREAD

**Issue by tomerlichtash** [wix/stylable#226]
```project.st.css``` imports ```style1``` and declares ```Item::title {-st-mixin: Style1}```.
```style1.st.css``` imports ```no-select``` and declares ```Style1 {-st-mixin: no-select}```.

**Expected result**: Style1 will contain rules from the original style definition, in which ```no-select``` will be embedded.

**Actual result**: The latter does not happen.

**Comment by tomrav** [comment]
Resolved in v5.1.0 
https://github.com/wix/stylable/releases/tag/v5.1.0

**Comment by brucelawson** [comment]
"CSS Mixin within a CSS Mixin" < from now on, this concept is to be referred to as a "Mix-inception".  Let it be so.
