### ISSUE TITLE
Escaping issues in type string :vars

### ISSUE THREAD

**Issue by tomerlichtash** [wix/stylable#227]
```
:vars {
   dash: "\2014";
}
.myClass::before {
  content: value(dash);
}
```
will transpile as:
```
.myClass::before {
  content: \2014;
}
```

Every escaping combination did not result in valid content value (```"'\2014'"``` will result the same).

However, the following transpiles correctly:

```
.myClass::before {
  content: "value(dash)"; 
}
```

But is very counterintuitive.

**Comment by tomrav** [comment]
Your current working solution is indeed counter-intuitive, and was fixed as a bug, and should not work anymore.
There is still definitely a gap in how Stylable handles strings and their escaping, which we hope to resolve in a future major version.

However, this is a solution that should work for you, using single quotes wrapped by double quotes, or vice versa.

```css
:vars {
   dash: "'\2014'";
}
.myClass::before {
  content: value(dash);
}
```
