### ISSUE TITLE
TS Mixin renders an extra whitespace before pseudo elements

### ISSUE THREAD

**Issue by tomerlichtash** [wix/stylable#229]
**TS Mixin**
```
module.exports = (content: any) => {
  return {
    "::before": {
      content: `\"___${content}___\"`
    }
  };
}
```

**CSS**
```
Item::item-title{
  -st-mixin: slidingDashMixin();
}
```

**Result: Extra whitespace before the pseudo element:**
```
.themea3567016190--root .item623790088--root .item623790088--item-title ::before {
  content: "yyyyyyyy___-___yyyyyyyyyyyyy";
}
```

**Comment by tomrav** [comment]
This is behaving as expected.
By writing the inner selector starting immediately with pseudo selector (`::before`) you get a descendant selector.

If you wish to concatenate your classes (`.item623790088--item-title::before`) add an `&` to your selector: `"&::before": {`
