### ISSUE TITLE
Can I haz Less as compilation target?

### ISSUE THREAD

**Issue by ydaniv** [wix/stylable#232]

**Comment by tomrav** [comment]
Currently Stylable outputs vanilla css as its target. 
Could you please explain what do you mean by LESS as a compilation target?

**Comment by ydaniv** [comment]
I like LESS, I'm working with it. I'd like to stylable for styling components on top of the features LESS provides me with.

**Comment by idoros** [comment]
Do you mean working in LESS syntax combined with Stylable syntax and compiling them both to CSS?

`LESS > Stylable > CSS`

**Comment by ydaniv** [comment]
Basically, yes. Perhaps I'm missing something trivial, but I don't see any reason not to. I'll drop by tomorrow.

**Comment by ydaniv** [comment]
Was dismissed as out of scope.
