### ISSUE TITLE
Imports with side effect

### ISSUE THREAD

**Issue by barak007** [wix/stylable#2735]
### Proposal Description

# Imports with side effect

Currently we have a few imports that we consider causing side effects, for example:

- -st-extends on imported class
- importing keyframes
- importing layer

When we encounter them we inject the import to the generated `js` module as "hard dependency".

That is a poor list that does not cover all the cases. and on top of it we only look at a single dependency level.

This is based on the assumption that component files usually does not cause global side effects. 
That's a good practice in general, but not true then other kind of file purposes are used, like `global.st.css` or `theme.st.css` or `common.st.css`.

We need to find a way to detect side effects in a more robust way. and maybe even allow the user to declare them.

The driving force of this is the stylable optimization. 
Initially we didn't report any hard dependency between stylable files. that had the effect of allowing the stylable JS modules to split between chunks. 
Today we report only the mentioned side effects as hard dependencies. that means that the stylable JS module will be in the same chunk as the file that caused the side effect. this is important when you start loading the css in the JS.

### 1. add annotation to the import

```css
@st-import "./file.st.css"; /* implicit side-effects */
@st-import Name from "./file.st.css" side-effects;
/* with maybe layer in the future */
@st-import Name from "./file.st.css" side-effects layer(base);
```

These files will be imported via the JS module, and will be reported as hard dependencies.

### 2. add annotation to the file

```css
@st-side-effects;
```

When importing this file, it will be reported as hard dependency. and will be imported via the JS module.

#### Open questions

- how does deep dependencies work?
- how does it work with theme files?

### 1. add annotation to the file

```css
@st-theme;
```
The JS module of this file will not import any other file.

**Comment by idoros** [comment]
Closing this due to automatic resolving of side-effects in #2786
