### ISSUE TITLE
Import CSS files.

### ISSUE THREAD

**Issue by dangreen** [wix/stylable#274]
How I should import and apply simple css files? Normalize.css for example.

**Comment by idoros** [comment]
Currently Stylable doesn't import/load from native CSS imports. 

You can configure webpack to load native `.css` files and import your bootstrap `.css` separately from javascript. Our [boilerplate](https://stylable.io/docs/getting-started/install-configure#write-your-own-project-based-on-a-stylable-boilerplate) is already configured for this. If you prefer to manually setup your project, it is important to configure the CSS loader to ignore the `.st.css` extension.

We could allow an import of native CSS that will simply output the native CSS without namespacing before the importing file.

**Comment by idoros** [comment]
You can see our boilerplate's relevant Webpack configuration [here](https://github.com/wix/stylable-scripts/blob/v0.3.2/config/webpack.config.prod.js#L173).
`/(?!<\.st)\.css$/` - this means `.css`, but not `.st.css`.
