### ISSUE TITLE
Stylesheet does not get applied when using Next.js 13

### ISSUE THREAD

**Issue by srmagura** [wix/stylable#2773]
### Actual Behavior

Repro project: https://github.com/srmagura/stylable-testbed

In dev and prod, the styles are not applied. In production mode, the stylable CSS is added as a `<script>` tag, which may provide a clue as to what is happening.

**Edit:** Actually, I think this is a problem with the new `app` directory rather than Next.js 13 itself. I created a different project which I thought was Next.js 12, but I was actually using Next.js 13 with `pages`. It works in this second project.

### Expected Behavior

The Stylable styles are applied to the document.

### Version

@stylable/core@5.2.1, @stylable/webpack-plugin@5.2.1

### Relevant log output

```shell
Not getting anything interesting in the logs.
```

**Comment by tomrav** [comment]
Hey, we just released a new version of Stylable (`v5.7.0`), which includes a new webpack flag, meant for next 13 app directory mode.

See more about how to use it here: https://stylable.io/docs/getting-started/nextjs-integration/#app-directory

We'd love to hear back if it worked as expected, and if not what went wrong.
