### ISSUE TITLE
build stylable without filesystem

### ISSUE THREAD

**Issue by ahoyahoy** [wix/stylable#2795]
### Describe your issue

How to use stylable without webpack or nodejs? Memfs for example or complete programmable?

**Comment by ahoyahoy** [comment]
O found it here :)
https://github.com/wixplosives/stylable-playground

**Comment by idoros** [comment]
I'm glad you found it, although just to be fair, the specific playground repository you found is not our current playground and is not maintained and not everything that is exposed is meant to be official stable API and might change in the future.

We are working on documentation for the programmatic API and will probably have the stable parts of it on the site next week. Feel free to share any use cases you might have and feel we should support so we know what to focus on.

**Comment by ahoyahoy** [comment]
thank you for your reply.
Thanks to that, I understood better how it works, but I haven't been able to get it working yet.

https://github.com/wix/stylable/issues/2796

I look forward next week then :))

**Comment by ahoyahoy** [comment]
My use case:
I just need to build my *.st.css from database, not from filesystem.
