### ISSUE TITLE
question: how to get final css

### ISSUE THREAD

**Issue by ahoyahoy** [wix/stylable#2796]
### Describe your issue

How to build sources programmatically into final css?

I tried `build` function from `cli` package.
I'd like to have resolved each file to final css, but result is still .st.css?
Also when I use param `bundle`, the file has resolved deps like funcions or colors, but there is still unresolved `-st-extends: Button`

I get same result when I'm trying to make ast  from `stylable.transform`

```
const files = {
    '/index.st.css': `
        :import {
            -st-from: './project.st.css';
            -st-named: active, danger;
        }
        :import {
            -st-from: './button.st.css';
            -st-default: Button;
        }
        .root {}

        .okButton {
            -st-extends: Button;
            color: value(active); 
        }

        .okButton::label {
            font-size: 1.5em;
        }

        .cancelButton {
            -st-extends: Button;
            color: value(danger); 
        }

    `,
    '/button.st.css': `
        :import {
            -st-from: "./formatter";
            -st-default: colorGreen;
        }

        .root {
        background: colorGreen();
        }
        .label {}
        .icon {}
    `,
    '/project.st.css': `
        :vars {
            active: green;
            danger: red;
        }
    `,
    '/formatter.js': `
        :vars {
            active: green;
            danger: red;
        }
    `,
}
```

**Comment by idoros** [comment]
`stylable.transform` is probably the way to go. Unfortunately `-st-*` declarations are removed in a separate optimization process that is called by the integrations. Moving this to the transform process has been on our todo list for awhile, I will make that happen this week, and the next version will remove `-st-*` declarations in `stylable.transform`.

If you use the transform on stylable, you will get `{ meta, exports }`, and you can read the final CSS from `meta.targetAst.toString()` and the mapped namespaced symbols on the `exports`.

The CLI internal `build` function can generate `.css` files with `outputCSS: true` and can run **ALL** optimizations with `optimize: true`, that includes removing the `-st-*` declaration. But I'm not sure you want the dependency on the CLI for your programmatic flow.

**Comment by ahoyahoy** [comment]
yeah stylable.transform is perfect. I look forward to your next update.
A predefined object (or documentation) for properly setup **memory fs** would also be useful.
requireModule and resolveNamespace

Thanks for your work btw! This is the best css tool ever :)
I immediately adopted it for all react projects and now I'm trying to impletent it in our low-code platform.

**Comment by idoros** [comment]
so new version [5.6.0](https://github.com/wix/stylable/releases/tag/v5.6.0) is out and should remove stylable build declarations by default for production mode.

Documentation should be updated soon
