### ISSUE TITLE
Tree-shaking removes code when imported from index.st.css

### ISSUE THREAD

**Issue by amiryonatan** [wix/stylable#283]
We have an index file containing: 
```
:import {-st-from: "./dist/src/components/Component/Component.st.css";-st-default:Component;}
Component{}
```

When we use it directly from `index.st.css`:
```
  :import {
    -st-from: "wix-ui-core/index.st.css";
    -st-named: Component;
  }

.root {
    -st-extends: Input;
}
```

Everything under the `-st-extends` won't be added to the bundle.

**Comment by idoros** [comment]
@amiryonatan - can you confirm [version 5.3.0](https://github.com/wix/stylable/releases/tag/v5.3.0) solves this issue for you?

**Comment by amiryonatan** [comment]
@idoros Yeah, thanks!
