### ISSUE TITLE
stylable build error with storybook 7

### ISSUE THREAD

**Issue by ahoyahoy** [wix/stylable#2852]
### Actual Behavior

I can't build project using storybook 7
`npm run storybook`

```
ModuleBuildError: Module build failed (from ./node_modules/@stylable/webpack-plugin/dist/loader.js):
```

repo: https://github.com/ahoyahoy/stylable-storybook

### Version

5.9.0

**Comment by idoros** [comment]
Hey, you need to configure other css loaders to ignore stylable files, we have a utility function available in `@stylable/webpack-plugin` that handles this. Checkout the [Storybook getting started page](https://stylable.io/docs/getting-started/storybook-integration) on our site for the example.

**Comment by ahoyahoy** [comment]
Hi Idoros,

I'm sorry, I forgot to include this while creating a minimal example.

I have updated the repository, but I'm still getting the same result.

**Comment by ahoyahoy** [comment]
hey :)
Sorry again
something is wrong with my sample repo.
I tried to make a complete new project and it works fine.
