### ISSUE TITLE
how to import css file in .ts file?

### ISSUE THREAD

**Issue by linmodev** [wix/stylable#308]
how to import css file in .ts file?

```ts

import * as React from "react";
import { Component } from "react";
import * as style from "./Button.st.css";

export default class Button extends Component {
  render() {
    return (
      <button>
        <span className="icon" />
        <span className="label">Submit</span>
      </button>
    );
  }
}
```
errors : can't find module

**Comment by tomrav** [comment]
If you're not using our boilerplate project starter, then you currently have to manually add the stylable typings to your project.

You can find a working `globals.d.ts` file [here](https://github.com/wix/stylable-scripts/blob/master/template/src/globals.d.ts)

We will make sure to address this issue in a future release and make this process automatic.
