### ISSUE TITLE
`:global()` eats commas

### ISSUE THREAD

**Issue by dangreen** [wix/stylable#309]
```css
:global(
	body, a, b
) {
	test: test;
}
```
emits
```

	body a b
{
	test: test;
}
```

**Comment by barak007** [comment]
Hi,
Thanks for the issue report.
:global dose not support multiple selectors right now.
as an alternative you can create the selector like this.
```css
:global(body), :global(a), :global(b) {}
```
We do not have plans to implement it soon. but maybe it should warn you when this scenario happens.
I have opened an issue #310 to fix it.
