### ISSUE TITLE
Namespaced custom properties

### ISSUE THREAD

**Issue by Scott-MacD** [wix/stylable#312]
Would really love to see a way to namespace css custom properties in a manner similar to how pseudo-classes/data attributes are handled. This would make it possible to set custom properties on a component level and have it be propagated to it's inner DOM without worrying about namespace collisions on child components.

Then we could do something like:
```javascript
export default ({offset = 0, length = 3}) => {
    const cssProps = transformProps({offset, length});
    // returns eg. "--MyComponent-offset: 0; --MyComponent-length: 3;"

    return html`
        <div class=${style.root} style=${cssProps}></div>
    `;
}
```

To make this possible the compiler would have to make this transformation on the generated stylesheet.

**Comment by barak007** [comment]
Hi, thanks for the request. 
We have plans to implement more deep support for custom properties.

It should include: 
* Way to import them in stylesheets and use them as overrides.
* Type validation for the property value.
* Javascript runtime creation.
* Global css properties access.

Let me know if you have any more insight on this topic, I would love to hear them.

Barak.

**Comment by Scott-MacD** [comment]
Thanks and really glad to hear it.

I'm already really happy with this preprocessor already and even more-so with the direction things seem to be heading. I think this pretty much covers all the use cases I've encountered so far. I'm assuming "scoping" doesn't mean it will have automatic root scoping as per https://github.com/wix/stylable/issues/217, but rather would just get added to whatever class you add it to, as this would likely cause similar issues to those I mentioned in that issue.

For whatever it's worth, I've been working with this together with [hyperHTML](https://github.com/WebReflection/hyperHTML) and it's been working wonderfully. hyperHTML lets you set up custom formatters for the type of data that you pass it, so if stylable had an api in the javascript runtime to map custom property names to their scoped versions I could easily write a formatter that would allow me to do something as concise as:

```js
export default state => hyperHYML.wire(state)`
    <div class=${style.root} style=${{cssProps: state}}>${state.name}</div>
`;
```

**Comment by brucelawson** [comment]
@Scott-MacD out of interest, is anything you've built using Stylable on the public web anywhere? We'd love to see it!

**Comment by Scott-MacD** [comment]
The project I’m working on right now that is using stylable is part of some tooling for medical presentations that are designed to run offline on an iPad as HTML/css/js, but I can’t really show that due to regulatory reasons. We’re going to be rebuilding our agency website in the near future however and I’d like to make stylable part of the tech stack for it, though I still have other parts of the tool chain I need to sort out. The end goal is to pre-compile to static assets as much as possible, then add in extra SPA like enhancements after the initial page load. Happy to link you to it once it’s complete, which may be a month or so from now.

**Comment by brucelawson** [comment]
Great, thanks!

**Comment by tomrav** [comment]
Continued discussion in #247, closing.
