### ISSUE TITLE
scopeSelector fails to handle global selectors

### ISSUE THREAD

**Issue by amir-arad** [wix/stylable#318]
when running `stylable.createTransformer().scopeSelector(meta, rule.selector).selector`

on a global selector, I'm getting selectors with the original global expression, which is not a legal selector I can use in the DOM.

currently I need to `.replace(/:global\((.*?)\)/g, '$1')` it myself. 

It'd be nice to get a simple API to turn any stylable selector (with optional scope argument) into something that can be run in the dom, or null / throw with explicit error if it's not possible.

**Comment by tomrav** [comment]
This API is deemed as working by design. Scope selector only scopes and does not transform.
We can consider an API for this actual full selector transformation.
