### ISSUE TITLE
please export native functions detection logic

### ISSUE THREAD

**Issue by amir-arad** [wix/stylable#320]
please export and support nativeFunctionsDic  from 'src/native-reserved-lists' , or more specifically export `isNativeFunctionName(funcName:string):boolean`, as we need to depend on it for the VSCode plugin.

**Comment by idoros** [comment]
I think this shouldn't be a static function. Because "native" for 1 build isn't necessary for another. 

Will it work for you as an API on the Stylable instance itself? so we can set some default for now and later allow to modify by configuration?

**Comment by amir-arad** [comment]
currently we're (@tempit ) [about to import](https://github.com/wix/stylable-intelligence/pull/219/files#diff-4e7b8b91f894f2c5832204868eb8803dR18) ```{ nativeFunctionsDic } from 'stylable/dist/src/native-reserved-lists'```. that will make it part of the de-facto API of stylable for the language services. we need a substitute API that will be supported.

**Comment by barak007** [comment]
It's already exposed from index. forgot the note in the release,
