### ISSUE TITLE
Separate stylable to multiple packages

### ISSUE THREAD

**Issue by AviVahl** [wix/stylable#327]
Writing down some of the thoughts regarding package separation.

Main packages:
- parser: uses [postcss](https://github.com/postcss/postcss), with additional required processing by us.
- transformer: should it be a postcss js plugin?
- generator: to print actual css assets
- css-runtime: isomorphic runtime that stylesheets use to register themselves. It should support browser and SSR scenarios.
- language services: expose diagnostics and type information about stylable stylesheets.
- test-utils: helpers to test styles and target dom elements using style API.

Integrations:
- webpack
- node
- jest transformer (?)
- vscode extension (in a separate mono-repo?)

Would be great if we start using the `@stylable` npm scope to group packages together in `node_modules` .

**Comment by barak007** [comment]
* stylable-parser
* stylable-core 
* runtime
-----
* stylable-program
* test-kit
* cli
* lang-server
* infra / utils
-----
* webpack-plugin
  * extentions 
* require-hook
* jest-transform
-----
* vscode plugin

**Comment by tomrav** [comment]
Resolved in #402

Finalized migration to mono-repo with move to NPM scoped packages.
