### ISSUE TITLE
stylable-scripts: update from upstream react-scripts

### ISSUE THREAD

**Issue by AviVahl** [wix/stylable#328]
`react-scripts` recently updated to webpack-4, which means we can remove our own forks of `WatchMissingNodeModulesPlugin` and `InterpolateHtmlPlugin`.

We should also pull further fixes from upsteam and discuss supporting external css files in `stylable-scripts` (for better operation with third-party non-stylable libraries).

**Comment by tomrav** [comment]
Irrelevant.
