### ISSUE TITLE
console warnings

### ISSUE THREAD

**Issue by lbelinsk** [wix/stylable#333]
wix-style-react `<ToggleSwitch>` uses the core ToggleSwitch. There is one line in the `st.css` file which triggers a warning:

https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/src/components/ToggleSwitch/ToggleSwitchLayout.st.css#L68

https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/src/components/ToggleSwitch/ToggleSwitchLayout.st.css#L73

![image](https://user-images.githubusercontent.com/18248989/40655464-1bba58c6-634a-11e8-8247-fe5eacb053d5.png)

This is happening for a lot of projects, so please try to take care of it as soon as possible.

**Steps to reproduce**
- Clone Ecom
- install this package which lies inside the mono-repo: https://github.com/wix-private/ecom/tree/master/client/wixstores-dashboard/wixstores-dashboard-tax
- Run `npm start`

**Comment by lbelinsk** [comment]
@barak007 @idoros

**Comment by idoros** [comment]
created a smaller issue for this: #334 

Note that there is a [feature request](https://github.com/wix/stylable/issues/292) (by you), we can implement, to polyfill a basic `:dir()` pseudo class

**Comment by lbelinsk** [comment]
@idoros at the moment, yes (for rtl)
