### ISSUE TITLE
Make enum "default" when listing possible values in custom state parameters

### ISSUE THREAD

**Issue by brucelawson** [wix/stylable#339]
Why do I have to write

`-st-states: man(enum(Tom, Ido, Arnon, Bruce)), mood (enum (grumpy, drunk, stoned, resignedToFate));`

rather than 

`-st-states: man(Tom, Ido, Arnon, Bruce), mood (grumpy, drunk, stoned, resignedToFate);`

but isn't it obvs if I have a parenthetical comma-separated list, that it's enum fun?

**Comment by idoros** [comment]
@nadavov @barak007 - what do you think, should we default to enum when passing a comma separated list?

**Comment by tomrav** [comment]
We're going to decide against this syntax sugar as it would limit us in the future when extending states API and would force a breaking change.
