### ISSUE TITLE
Style component className in docs not working

### ISSUE THREAD

**Issue by ekaoddlass** [wix/stylable#340]
The documentation (["Component Basics"](https://stylable.io/docs/guides/components-basics)) gives an example of styling elements using the `className` property:

```
/* button.ts */
render () {
    return (
        <button>
            <span className="icon"/>
            <span className="label">Submit</span>
        </button>
    );
}
```
```
/* button.st.css */
.icon {
    background-image: url('./assets/btnIcon.svg');
}
.label {
    font-size: 1.2em;
    color: rgba(81, 12, 68, 1.0)
}
```

When I run the Stylable app installed through create-react-app, the above code does not work. It does work when an object is passed as the class name (`<span className={style.icon}/>`).

Does the doc need to be updated or is it a different usage altogether?

**Comment by idoros** [comment]
Thank you for pointing this out, there is definitely missing information and outdated content there. The examples in this page are using `wix-react-tools` to wrap the React components (you can see that in the panel SFC example).

**Comment by brucelawson** [comment]
Thank you @eka!

**Comment by brucelawson** [comment]
Team: from Eka's twitter feed  "Kinda gave up for now. I didn't even manage to run CSS Blocks (could build fine but kept getting errors running). Stylable is closer to what I need --underlying logic feels solid, too-- but the learning curve is a bit too steep for me as a beginner."

https://twitter.com/ekaoddlass/status/1002997285066690562

**Comment by brucelawson** [comment]
@ekaoddlass - Personally, I find it easier to learn from an existing project that I can tweak and immediately see the results. Our Mr Potato Bruce project was made for that: https://potatobruce.io/ (the link to the repo with build instructions that even I can follow is on the footer). The main Stylable file is https://github.com/wix/potato-bruce/blob/master/src/components/app.st.css

**Comment by brucelawson** [comment]
@AnnieLR can you look at this bit of documentation plz plz plz?

**Comment by ekaoddlass** [comment]
@brucelawson Yes! I’ve cloned and started dissecting the potato-bruce repo. Already managed to create a component (moved the app Footer to a separate component), now looking at how states are applied. I agree, it’s easier to learn by looking at sample project — and this one is particularly well-organized and has ample comments/annotations. 👍🏾

Reason I gave up had waaay more to do with Typescript rather than Stylable, never having worked with the former before (2am tweets are not the best in terms of clarity, are they? 🤔😅). I’ll need to get a stronger, more in-depth grasp of JS and React first in order to get Typescript to do what I want it to do.

If there is a future version/fork of Stylable that works with regular React JSX (and even better, static sites generator like Next or Gatsby!), I think it will be a breeze to use.

**Comment by tomrav** [comment]
We're definitely considering additional integrations, though have nothing concrete to share at the moment.

I've gone over the out of date doc, and fixed it to be relevant again.
You can try giving it a read and see if it makes more sense to you now - if it doesn't, I'd love to know which parts could use improvement.

https://stylable.io/docs/guides/components-basics
