### ISSUE TITLE
Feature proposal: Dynamic styles

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#349]
> Note: This proposal used to exist as a PR that is now closed, re-opening as issue.

# Dynamic Styles

Here at **Stylable** we consider writing CSS through runtime JS as a last resort. It causes huge browser redraws and generally needs a lot of runtime code to run.

In most cases when you need to change style attributes dynamically, it is better to use inline-styles.

If you find yourself needing to use dynamic CSS in your application, you can import and use `renderCSS` and `removeCSS` from the **Stylable** runtime.

## Render CSS

`renderCSS` uses a token to ensure dynamic CSS doesn't leak between instances, old CSS is removed when dynamically changed, and CSS is not re-rendered unless it changed.

This token is returned by `renderCSS` and should be passed to it in subsequent calls by the same component instance.

This token should also be added to the render node of the overriding component root to allow scoping. This is done using the `data-style-token` attribute.

Params:

| Name | Type | Description |
|----|----|----|
| stylesheet | StylableStylesheet | the overriding components stylesheet |
| style | StylableDynamicCSS | the CSS override to render |
| token | string \| undefined | rerender-token |

Returns: `token`

## Remove CSS

`removeCSS` clears CSS created by render CSS.

If you have a lot of components using dynamic CSS, you should clear it when they are unmounted.

Params:

| Name | Type | Description |
|----|----|----|
| token | string | token of the CSS to remove |

## Example usage

A component that changes the background color of internal parts according to a component prop.

```tsx
import {renderCSS, removeCSS} from "stylable/runtime";
import style from "./my-comp.st.css";
import Gallery from "./my-gallery";
import * as React from "react";

export default class MyComp extends React.Component<{itemColor:string},{}>{
    private dynamicCSSToken:string;
    render(){
        this.dynamicCSSToken = renderCSS(style,{
            ".root::gallery::item":{
                'background-color':this.props.itemColor
            }
        }, this.dynamicCSSToken);

        return <div { ...style('root', {}, this.props) } data-style-token={this.dynamicCSSToken}>
            <Gallery/>
        </div>
    }
    componentWillUnmount(){
        removeCSS(this.dynamicCSSToken);
    }
}

```

This call to `renderCSS` generates the following CSS for `dynamicCSSToken="x"` and `itemColor="green"`.

```css
[data-style-token="x"] .example__root .example__gallery.gallery__root .gallery__item{
    background-color:green;
}

```

Issue raised by @barak007:
> How can we know the mapping of inner parts like ::gallery::item, as they are not present in the current stylesheet's runtime.

**Comment by idoros** [comment]
While there is a place for dynamic css, most of the cases can be solved using css vars today.

I'm closing this issue for now.
