### ISSUE TITLE
When diagnostic relates to declaration, send the declaration in the report instead of parent node

### ISSUE THREAD

**Issue by tempit** [wix/stylable#357]
In this case, a diagnostic about -st-default capitalization is issued, but the word in the report is  'tab' and the entire node is appended. 
Since it's impossible to know which occurrence of the string 'tab' is meant without knowing the logic of the diagnostic, stylable-intelligence places the message at the wrong place.

:import {
    -st-from: "../../components/tabs/tabs.st.css";
    -st-default: tab;
}

**Comment by tomrav** [comment]
resolved in #358
