### ISSUE TITLE
Error when using a default import as both element and mixin

### ISSUE THREAD

**Issue by tempit** [wix/stylable#372]
The code below throws a diagnostic error for the -st-mixin line - 'Unknown mixin "Comp"'
The error vanishes if removing the .root Comp block.

:import {
    -st-from: "./test.st.css";
    -st-default: Comp;
}

.root Comp {
    color: aquamarine;
}

.local {
    -st-mixin: Comp;
}

**Comment by idoros** [comment]
still happens after all. @barak please take a look at your fix that got lost in the git.

**Comment by barak** [comment]
Wrong Barak, you meant @barak007
