### ISSUE TITLE
Stylable Webpack Plugin and Autoprefixer

### ISSUE THREAD

**Issue by dangreen** [wix/stylable#373]
> You cannot use loaders with Stylable .st.css files

How I can use Autoprefixer with Stylable Webpack Plugin ?

**Comment by tomrav** [comment]
We are planning on integrating `Autoprefixer` into the `stylable-webpack-plugin` as a native option in the future.

Having said that, until we actually do offer that, you can add a `postProcessor` hook to your `stylable-webpack-plugin` configuration. (this is a brand new feature and is not yet documented, sorry :/).

I've added a test-case using the `Autoprefixer`, in PR #374, as a sanity on our end to make sure it works.

Sample config:
```ts
const autoprefixer = require('autoprefixer');
const postcss = require('postcss');
const autoprefixProcessor = postcss([autoprefixer]);

new StylableWebpackPlugin({
    // ... config ...
    transformHooks: {
      postProcessor: (stylableResult) => {
        autoprefixProcessor.process(stylableResult.meta.outputAst).sync();
        return stylableResult;
      }
    }
}
```

**Comment by dangreen** [comment]
@tomrav 
What about stylelint?
```
Error: Use process(css).then(cb) to work with async plugins
```

**Comment by tomrav** [comment]
Currently the hooks that Stylable integrates into are synchronous, which makes adding async plugins problematic. 

We can try and think of work arounds that we can implement - but for the moment those types of plugins are unsupported.

**Comment by tomrav** [comment]
Issue appears to be resolved, please open a new issue for further questions.
