### ISSUE TITLE
No diagnostic error for named import that doesn't exist

### ISSUE THREAD

**Issue by tempit** [wix/stylable#379]
This throws no error. Though the file test.st.css exists, it doesn't have a 'someVar' symbol

:import {
    -st-from: "./test.st.css";
    -st-named: someVar;
}

**Comment by tomrav** [comment]
This is an issue with when Stylable decides to issue diagnostics on imports.
At the moment, you'll get an error that `someVar` doesn't exist only when trying to use it (e.g. `color: value(someVar)`).

Diagnostics for imports in general need to be refactored to issue warnings without usage for both non-existing files and symbols.

**Comment by tomrav** [comment]
Closing in favor of #393
