### ISSUE TITLE
-st-extends documentation clarification needed

### ISSUE THREAD

**Issue by hepiyellow** [wix/stylable#394]
In this documentation page titled: "Extend Stylable Stylesheet"
https://stylable.io/docs/references/extend-stylesheet

It is written:
> "The checkBtn class has a label, which is a custom pseudo-element, and has a custom pseudo-class, toggled."

I think you meant to say that the `< ToggleButton/>` component (which the `./toggle-button.st.css` stylesheet is attached to it's root), has a `label pseudo element, ....

And I think the Javascript code of `< ToggleButton/>` would be helpful here, to understand how the `label` is defined.

**Comment by brucelawson** [comment]
WDYT, @AnnieLR ?

**Comment by idoros** [comment]
Documentation definitely needs an overall. Much that we learned and much that we missed.

> I think the Javascript code of < ToggleButton/> would be helpful here

We are trying to avoid connecting Component logic and style into a single entity (it's important for us to go in the direction that the style API is a separate definition that might be consumed by different component logic implementations)  - @tomrav - what do you think, maybe add a specific snippet with a React implementation in some cases (maybe go through various view implementations in the new site)?

@hepiyellow, how about changing the text to:

"the page component stylesheet contains the `.checkBtn` CSS class which extends the toggle-button stylesheet definition. Allowing us to target and style an internal `::label` pseudo-element,  a `:toggled` pseudo-class and any other style API inherited from toggle-button"

**Comment by tomrav** [comment]
Page in question has been re-written, seems to contain the requested change.
