### ISSUE TITLE
How to import global styles?

### ISSUE THREAD

**Issue by dangreen** [wix/stylable#416]
I have ["reboot" styles](https://github.com/TrigenSoftware/flexis-ui/blob/master/src/reboot.st.css).
[Earler with `-st-theme` I was able to apply this styles globaly.](https://github.com/TrigenSoftware/flexis-ui/blob/master/src/index.st.css)
How I can do it now?

**Comment by idoros** [comment]
Im not sure what you mean. Can you elaborate on the use case?

**Comment by dangreen** [comment]
@idoros 
Global styles: https://github.com/TrigenSoftware/flexis-ui/blob/master/src/reboot.st.css
My index.st.css: https://github.com/TrigenSoftware/flexis-ui/blob/master/src/index.st.css#L4
Applying index.st.css to my app: https://github.com/TrigenSoftware/flexis-ui/blob/master/.storybook/config.js#L15

I want to apply global styles, now without `-st-theme` (removed from docs, from stylable) I can't do that.

**Comment by dangreen** [comment]
```css
:import {
	-st-from: './reboot.st.css';
}
```

do nothing

**Comment by idoros** [comment]
The css js discarded because it is not used by any none stylable module. 

We need to add the ability to explicitly import st.css / css files into the output.

In the meantime try importing the global st.css file from your application root as well (just to cause it to be included in the css output)
