### ISSUE TITLE
Strip and warn about CSS breaking namespace characters

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#417]
Allowing special punction marks (such as `.`, `,`, `>`, etc..) can cause the resulting target selectors to break in various unexpected ways.

- [ ] Stylable should limit the `namespace` directive to only allow `a-z 0-9` characters in its value by stripping and warning about disallowed characters
- [ ] Must start with a letter
- [ ] Update docs to reflect this change

**Comment by idoros** [comment]
namespaces are currently escaped correctly and exported to js also seems fine ([example](https://wixplosives.github.io/stylable-playground/#state=%28%27files%21%28*%21%27%2540namespace%2520%255C%27%27%253A%255C%270-.root%2520.label%2520%28-%2520%2520%2520%2520color%253A%2520gold0%29-%27%29%7Eselected%21*%27%29*%27%252Findex.st.css-%255Cn0%253B-%25010-*_)).

Changing this is a breaking change that I think we can avoid for now.
