### ISSUE TITLE
Use with web components?

### ISSUE THREAD

**Issue by trusktr** [wix/stylable#420]
Can we use this with Custom Elements?

**Comment by idoros** [comment]
In case of `shadow dom` the api to target internal parts is not available today, so `custom pseudo element` won't be able to target the shadow dom.

You could still try to use [stylable to build a single component](https://twitter.com/wolframkriesing/status/1026880648018096128) (style withing the shadow dom)

With no shadow dom, just custom elements, you could possibly use stylable to build the style and scope it on the build.
