### ISSUE TITLE
Sass or PostCSS transpile step?

### ISSUE THREAD

**Issue by trusktr** [wix/stylable#421]
It'd be neat if we could use Sass or [postcss-preset-env](https://preset-env.cssdb.org/) as an intermediary transpile step to get more language features.

It would need some plugins to make it understand the stylable-specific syntax parts.

**Comment by AviVahl** [comment]
Currently, there is no simple config to just write a `postcss` preset name and have it loaded as part of stylable's processing.

Stylable's current implementation is sync-only, and thus can only run sync postcss plugins. There's a programmatic example showing how to run `autoprefixer`: https://github.com/wix/stylable/issues/373#issuecomment-403436282

`postcss-preset-env` is async and cannot be used or hooked as-is into Stylable's process.

There are future plans to allow specifying **any** postcss plugin.
