### ISSUE TITLE
CLI: `stc` does not report transformation errors

### ISSUE THREAD

**Issue by hepiyellow** [wix/stylable#431]
## What should change

I think we can have the `stc` report also warnings by default.
(Or we can add a logLevel argument.)

## Undefined variable is a warning

A very common error is an undefined variable (in a `value(foo)` function),
and it is considered a warning for some reason.
(While we're at it, shouldn't this be an error?)

**Comment by tomrav** [comment]
Turns out this wasn't exactly the issue, it only included errors from the processing phase and not the transformation. Will be resolved in next version.
