### ISSUE TITLE
improve hashing solution for SSR support

### ISSUE THREAD

**Issue by shlomitc** [wix/stylable#436]
## Current behavior
`Stylable` creates the class names and states hashes according to the absolute path of the file.

## The issue
When a project is built on one machine (creating the bundle) and then rendering with SSR on a different machine (production server) - the output class names are different.

## Suggested solution
Generate the hash according to the relative path (starting from the project folder).

Thanks

**Comment by shlomitc** [comment]
FYI @lbelinsk

**Comment by idoros** [comment]
Already under development :) - #435
