### ISSUE TITLE
Is it possible to add a selector prefix to all rules in a stylesheet?

### ISSUE THREAD

**Issue by hepiyellow** [wix/stylable#447]
For theming, our current solution in `wix-ui-core`, is to prefix every rule in the stylesheet with a `backoffice` root class.

[See this example](https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/src/themes/backoffice/button/button.st.css)

**Comment by tomrav** [comment]
I'm working on implementing this feature right now. :)
This issue is a duplicate of #411, so I'm closing it.
