### ISSUE TITLE
fusebox

### ISSUE THREAD

**Issue by vegarringdal** [wix/stylable#448]
Will only webpack be supported ?

Do you plan to support other bundlers like fusebox ?
[fusebox](https://fuse-box.org/)

**Comment by barak007** [comment]
Thanks for reaching out.
We will evaluate what such an integration would require, and will let you know as soon as we have further information.

**Comment by idoros** [comment]
I'm sorry about this issue being forgotten, as of now we simply don't have the capacity to support every bundler. Currently Webpack & Rollup (on the way) are being supported and hopefully we'll make it easier to integrate others at some point.

I'm closing this issue for now.
