### ISSUE TITLE
is the runtime required?

### ISSUE THREAD

**Issue by hulkish** [wix/stylable#451]
I am evaluating stylable, and would like to understand if there is a supported concept of no runtime required? For example, what if i wanted to use stylable directly as a replacement of css modules?

**Comment by idoros** [comment]
Stylable has 2 modes. CSS in JS and static (see `includeCSSinJS` and `createRuntimeChunk` flags in the [webpack plugin](https://github.com/wix/stylable/tree/master/packages/webpack-plugin)). By default, they are both set to false in production mode and like CSS Modules should produce a static CSS output.

**Comment by hulkish** [comment]
@idoros what do u mean by static? 

Ultimately i want my styles to live in a css file, or inlined on page. And, only reference the class names in js. Is this possible with stylable?

**Comment by idoros** [comment]
Yes. Stylable outputs a css file and leaves only the class names mappings in the js output (by default in stylable webpack production mode).

**Comment by tomrav** [comment]
Here's a sample config in the spirit of what @idoros has mentioned:

```ts
new StylableWebpackPlugin({ 
    outputCSS: true, 
    includeCSSInJS: false
})
```
