### ISSUE TITLE
Possibility of omitting first parameter in stylable runtime

### ISSUE THREAD

**Issue by Scott-MacD** [wix/stylable#473]
Any thoughts about simplifying the runtime API slightly so that the first parameter of the `style` function can accept a custom state object as an alias for `style.$cssStates` without requiring an element name?

Just trying to remove some boilerplate and provide a cleaner API so that `style.item` and `style({selected: true})` are both possible. The shorter alias for `style.$cssStates` is a lot easier to read when it is inlined in template strings for example. Up to this point I've been working around it by creating a simple wrapper function `const st = state => style.$cssStates(state);` but it would be nice to be able to use both these utilities under the same namespace.

Not hugely important, it's just a little easier to read hundreds/thousands of references similar to:
```javascript
const update = ({activeItem}) => render`
    <ul class=${style.root}>${items.map((item, i) => hyper(item)`
        <li class=${style.item} st-attrs=${style({active: activeItem === i})}>
            ${item.name}
        </li>
    `)}</ul>
`;
```

rather than:
```javascript
const update = ({activeItem}) => render`
    <ul class=${style.root}>${items.map((item, i) => hyper(item)`
        <li class=${style.item} st-attrs=${style.$cssStates({active: activeItem === i})}>
            ${item.name}
        </li>
    `)}</ul>
`;
```

Or the alternative of having to create a child wrapper function so that the result of style.$cssStates can be assigned to a variable:
```javascript
const update = ({activeItem}) => {

    const renderListItem = (item, i) => {
        const stateAttrs = style.$cssStates({
            active: activeItem === i
        });

        return hyper(item)`
            <li class=${style.item} st-attrs=${stateAttrs}>
                ${item.name}
            </li>
        `;
    }

    return render`
        <ul class=${style.root}>${items.map(renderListItem)}</ul>
    `;

};
```

Happy to create a PR.

**Comment by idoros** [comment]
I don't have any objections to adding another signature the main runtime mapper. @barak007 ? @tomrav ?

**Comment by tomrav** [comment]
After discussing the issue with @barak007, he raised the point that changing the `stylesheet` signature to be overloaded  might lead to some performance issues, or degregation.

As an alternative solution we could add a new export to the Stylable runtime, which would in turn expose the `$cssStates` method under a separate name.

How this might look, with your provided example:

```tsx
import style, { stStates } from './stylesheet.st.css';

const update = ({activeItem}) => render`
    <ul class=${style.root}>${items.map((item, i) => hyper(item)`
        <li class=${style.item} st-attrs=${ stStates({active: activeItem === i}) }>
            ${item.name}
        </li>
    `)}</ul>
`;
```
 
and how this might look using a simple JSX example:

```tsx
import style, { stStates } from './stylesheet.st.css';

function Comp({activeItem}) {
    return (
        <div className={style.root} {...stStates({ active: activeItem === i })}>
            Render me!
        </div>
    )
}
```

**Comment by Scott-MacD** [comment]
Makes sense.

I do like the idea of it being the same function as the existing `style` function as it already provides that functionality, but if it's going to cause performance issues that's not worth the trade off imo. Keeping these as separated dedicated functions is also arguably easier to understand.

If this method is going to be exposed directly as a module export, would it make sense to keep the same name as the existing method for consistency? ie `import style, {cssStates} from './stylesheet.st.css';`

**Comment by tomrav** [comment]
We'll be sticking with the `cssStates` function for now, I think it gets a bit easier to use in the `next` version, due to everything eventually becoming a class.
