### ISSUE TITLE
Improve namespace resolution for multi-dist projects

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#474]
Stylable's default namespace resolution function should take into account both `main` and `module` entries in the closest `package.json`. 

It should normalize the relative module path to the two entries so that they end up using the same string to hash.

**Comment by mykas** [comment]
Hi Tom, it seems that we have this issue happening to `wix-style-react` users quite often. When can we expect this fix ?

**Comment by mastertheblaster** [comment]
Also consider two projects/bundles to be loaded on the same page having the following configuration:
- Project A `wix-ui-core@2.0.17` and `wix-ui-backoffice@1.0.333`
- Project B `wix-ui-core@2.0.16` and `wix-ui-backoffice@1.0.333`

The hash function will try to create the following hashes for project A:
wix-ui-core@2.0.17/dist/src/components/deprecated/label/Label.st.css
wix-ui-backoffice@1.0.333/dist/src/components/Label/Label.st.css

And project B:
wix-ui-core@2.0.16/dist/src/components/deprecated/label/Label.st.css
wix-ui-backoffice@1.0.333/dist/src/components/Label/Label.st.css

The issue will appear cause classname for `wix-ui-backoffice@1.0.333` will be the same, but for Label comming from `wix-ui-core` will differ, and as a result we will see a red warning.

Maybe we can pass a seed for a hash function (aka main project name from package.json)?

**Comment by tomrav** [comment]
This issue has been resolved by introducing the `useNamespaceReference` flag to be used when publishing a library with our CLI.
