### ISSUE TITLE
Warning: unknown pseudo-state "after"

### ISSUE THREAD

**Issue by saarkuriel** [wix/stylable#475]
Hi,

I've used the following selector: `.root::step:not(:last-child):after`
and I get a warning thrown: `Warning: unknown pseudo-state "after"`

Is this expected? am I not using `after` correctly?

**Comment by tomrav** [comment]
According to the CSS spec `::after` is a `pseudo-element` (double-colon) and not a `pseudo-class` (single colon). Try adding another colon. :)

**Comment by saarkuriel** [comment]
Yeah I was afraid this syntax is somehow interpreted differently by stylable... A bit confusing.
Thanks!
