### ISSUE TITLE
When I use the pseudo-class selector :window-inactive, it doesn't work

### ISSUE THREAD

**Issue by comeriven** [wix/stylable#480]
example:
.scroll::-webkit-scrollbar-thumb:window-inactive {
    background: rgba(255, 184, 36, .4);
}
In console of Chrome, I get a warning ant it not work!
My Chrome is latest version!
hope is good!

**Comment by idoros** [comment]
`window-inactive` is [non-standard](https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-window-inactive) and only works with the `-moz` vendor prefix.

Stylable warns on any selector that is non-standard or not Stylable custom selector. However this warning won't change/remove your selector, so it should work fine if you only run your application in Firefox.
