### ISSUE TITLE
Optional class name in the style function

### ISSUE THREAD

**Issue by idoros** [wix/stylable#544]
**relates to `next` version - [Stylable 2.0](https://github.com/wix/stylable/pull/494)**

In most cases the `className / class` property of components is optional with no default, so currently every optional string class value needs to be checked from the outside:
```ts
style(classes.root, optionalClassName || '')
style(classes.root, {}, optionalClassName || '')
```

It would be nice if the CSS `style` function that builds the class property string would accept `undefined` as well as `string | StateMap` (in that case also the 3rd classes array should accept a sparse array):

```ts
export interface RuntimeStylesheet extends StylableExports, RenderableStylesheet {
    ...
    style: (context: string, stateOrClass: string | StateMap | undefined, ...classes: Array<string | undefined>) => string;
}
```

**Comment by tomrav** [comment]
Resolved in latest `next` release.
