### ISSUE TITLE
Quirks in style function that builds the class property

### ISSUE THREAD

**Issue by idoros** [wix/stylable#546]
**relates to `next` version - [Stylable 2.0](https://github.com/wix/stylable/pull/494)**

* Appending empty strings:
`css.style('xxx', {}, '', '', '', '', '')` 
<pre>
outputs: "xxx     "
expected: "xxx"
</pre>

* Transforms extra classes for **invalid** 3rd argument (shouldn't accept array):
`css.style('xxx', {}, ['a','b'])`
<pre>
outputs: "xxx index2467813853---01-a index2467813853---11-b"
expected: "xxx" + warning?
</pre>

* StateMap transforms array (probably related to the previous one):
`css.style('xxx', ['a','b'])`
<pre>
outputs: 'xxx index2467813853---01-a index2467813853---11-b'
expected: 'xxx' + warning?
</pre>

**Comment by tomrav** [comment]
Resolved in latest `next` version.
