### ISSUE TITLE
`@stylable/jest` Support configuration of st.css files processor

### ISSUE THREAD

**Issue by NitayRabi** [wix/stylable#567]
Currently [@stylable/jest](https://github.com/wix/stylable/blob/master/packages/jest/src/jest.ts) returns a processor with default values. 
Please implement a factory function to allow overriding default configuration.

Related to - https://github.com/wix/yoshi/issues/1189

**Comment by NitayRabi** [comment]
Hey @tomrav @barak007 - is there an ETA on this?

**Comment by tomrav** [comment]
Not yet, sorry. 
Hopefully we'll get to this in the coming couple of weeks.

**Comment by tomrav** [comment]
This has been implemented. `@stylable/jest` exports a factory that can accept a stylable configuration.

```ts
function processFactory(
    stylableConfig?: Partial<StylableConfig>,
    factoryOptions?: Partial<Options>
)
```
