### ISSUE TITLE
CLI export is invalid for node usage

### ISSUE THREAD

**Issue by idoros** [wix/stylable#608]
When using the `stylable/cli` to generate `st.css.js` files that can be used in Node,js, the output contains both JS modules and the original `.st.css` files that can be used when publishing as a 3rd party. The issue is that Node will prefer the exact match and will try to load the source files instead of the generated `.st.css.js` files.

There are several ways to solve this:
- offer a way to generate only for the required purpose (node / src-publish)
- make the stylable loader handle `.st.css.src` files and output with that extention

At the moment for my case I generate all the files and then delete all the copied stylable source files 🙁

**Comment by tomrav** [comment]
Resolved in #622, the CLI will no longer copy over source css files by default, and will now require the `--css` flag to be enabled in order to do so.
This is partial solution to the issue, and should be explored further.
