### ISSUE TITLE
Create handling for :hover for touch devices

### ISSUE THREAD

**Issue by LeonidLevi** [wix/stylable#61]
### Problem:
- `:hover` handling on mobile is bad (hover is activated on touch, but doesn't get deactivated until you touch something else), so **we need to disable hover on mobile**
- `:active` on mobile provides the same functionality as `:hover` on desktop. So it is preferred that we **remap `:hover` to `:active` on mobile**, unless `:active` is explicitly specified by the user.

### Proposed solution:
- When encountering `:hover` in CSS, auto-create a media query, something along the lines:
```
@media (hover: none) {
    .root:hover {
           /* reset the rules */
    }
    .root:active {
        /* put original hover rules here */
    }
}
```
- Do the above unless there is also a `:active` selector present for the same selector. In that case, just reset/remove the hover.

**Comment by tomrav** [comment]
This is out of scope for Stylable
