### ISSUE TITLE
value() not resolved in native function repeat()

### ISSUE THREAD

**Issue by MSiliunas** [wix/stylable#633]
## Problem
Looks like `value()` function is not working inside native function `repeat()`. Also - `repeat()` is not white-listed.

## Code
```
:vars {
  smallWidth: 24px;
}
.root {
  display: grid;
  grid-gap: 12px;
  -st-states: size(string);
}
.root:size(small) {
  grid-template-columns: repeat(auto-fill, value(smallWidth));
}
```
## Expected result
`value(smallWidth)` to be resolved to `24px` and following css generated
```
grid-template-columns: repeat(auto-fill, 24px)
```

## Actual result
`value()` is not resolving the variable and following **incorrect** css is generated:
```
grid-template-columns: repeat(auto-fill, value(smallWidth));
```

**Comment by tomrav** [comment]
Your case specifically happens with native functions that have not been white-listed in Stylable.

We need to release a fix to replace inner usage of stylable `value()` even when we do not recognize the function (regardless of unknown native function or missing formatter, diagnostic warning will still be issued).

**Comment by tomrav** [comment]
This has been fixed in the latest release.
