### ISSUE TITLE
Integration with gatsby

### ISSUE THREAD

**Issue by Nicotu** [wix/stylable#654]
Trying to figure out how to integrate stylable with gatsby but we're facing some errors. Here's the link to the original issue. https://github.com/gatsbyjs/gatsby/issues/14487

**Comment by tomrav** [comment]
Glad to see you've gotten this working in the other issue. Closing this for now, if you have any questions feel free to open another issue.

**Comment by superhawk610** [comment]
For anyone that runs across this issue in the future, I've created a Gatsby plugin [here](https://github.com/superhawk610/gatsby-plugin-stylable) that makes this process much easier.
