### ISSUE TITLE
normalize / reset / global styling

### ISSUE THREAD

**Issue by azharulc** [wix/stylable#670]
Hi,

I'm trying to figure out where i can add a normalise / reset file and what the best practice for it would be. I am also trying to figure where to import my font faces I cant seem to be able to figure it out

I'm using react through Gatsby and cant figure out what the right thing to do is.

**Comment by tomrav** [comment]
Can you please share an example of the CSS reset you would like to use?
Based on its structure we can advise on how to best integrate it into your project.

**Comment by idoros** [comment]
I think it would be helpful to automatically append normal CSS file content, with no namespacing, when imported from an st.css file.

That way a reset CSS can be brought and updated normally and easily be used by a Stylable project.

**Comment by azharulc** [comment]
Could you give me an example of this? 

say for example just to keep it simple I want to add a new font face add apply it globally.

I have the following code in a file which i would want across all my components without having to import it all the time-

```
@font-face {
    font-family: Rubik;
    src: url("../../../assets/fonts/rubik-medium.ttf");
  }
```

where should it go? and how should should it be globally added?

**Comment by tomrav** [comment]
We've tried playing around with stylable and gatsby and encountered some issues with the published plugin and its configuration. We'll open a PR to make it work and sort out its production mode along the way.

As for your question about resets/font-faces, you can simply have a plain css file with your resets and/or font definitions and import that in the `js` root of you application, these will then apply down the DOM tree.

**Comment by idoros** [comment]
I put the `@import` in my main theme.st.css file:

```css
@import url('https://fonts.googleapis.com/css?family=Roboto');

.root {
    font-family: 'Roboto', sans-serif;
}
```

**Comment by azharulc** [comment]
I decided to just import it in my root template, it seems to have worked and apply all the styles where I needed them.

Thanks for your help
