### ISSUE TITLE
wrong 'unscoped element...' warning

### ISSUE THREAD

**Issue by nirdom** [wix/stylable#686]
When adding a css rule with the following structure

```css
TagName.className
{
   /* ... */
}
```
I get an error of `unscoped element "TagName" will affect all elements of the same type in the document`. This error shouldn't appear since the selector is specific for elements with the class `className`.

For example, the following rule will produce the error `unscoped element "div" will affect all elements of the same type in the document`:

```css
div.root
{
   /* ... */
}
```

**Comment by tomrav** [comment]
Resolved in #1624
