### ISSUE TITLE
Animating SVGs

### ISSUE THREAD

**Issue by azharulc** [wix/stylable#716]
I would like to target paths within SVGs so that I can animate them, I am able to import them into my project fine using gatsby-plugin-react-svg but i cant seem to be able to apply any styles onto them, for example:

I have an SVG:
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
	 viewBox="0 0 24 24">
  <path className="first-line" stroke="#000000" stroke-width="1" d="M12,10.6L6.4,5L5,6.4l5.6,5.6l1.4,1.4l5.6,5.6l1.4-1.4L13.4,12L12,10.6z"/>
  <path className="second-line" stroke="#000000" d="M19,6.4L17.6,5L12,10.6L10.6,12L5,17.6L6.4,19l5.6-5.6l1.4-1.4L19,6.4z"/>
</svg>
```

which I import at the top of my component:

```
import CloseIcon from "../../../assets/images/close.svg"
```

Then I add my stylable class later on in the file
```
<CloseIcon
          className={style(classes.closeIcon)}
          onClick={this.deactivateSearch}
        />
```

and then in my .st.css I use

```
.closeIcon .first-line {
  display: none;
}
```

but the first stroke does not disappear, what am i doing wrong?

Thanks

**Comment by tomrav** [comment]
I think what is happening is that you are writing a Stylable selector, which gets automatically namespaced. This means that the `.first-list` class actually gets transpiled to something like `.comp__first-line435534` (made up hash numbers). 

In order to target classes from 3rd-party packages which are not written in Stylable, you should use the `:global(<selector>)` feature.

So your CSS should probably be:
```css
.closeIcon :global(.first-line) {
  display: none;
}
```

**Comment by idoros** [comment]
You might still have mismatched selectors.

What @tomrav wrote is correct, the loader doesn't transform the classnames in the same way that Stylable does,  However according to the [svg-react-loader](https://github.com/jhamlet/svg-react-loader) docs it does transform them to have a prefix based on the file basename. 

So even with the `:global(.first-list)`, the result SVG might have `filename-first-list` as a classname. So you can account for that in your global selector or use the `classIdPrefix` loader param to override the prefix.

Hope that helps.

**Comment by azharulc** [comment]
Brilliant, I'll try it out this evening - I don't recall seeing `:global` feature before. Thank you for the advise 👍

**Comment by tomrav** [comment]
Hope you get it working, you can read more about it [here](https://stylable.io/docs/references/global-selectors).
