### ISSUE TITLE
Missing native-css functions in ignore list

### ISSUE THREAD

**Issue by NitayRabi** [wix/stylable#788]
We get a warning for using `rect` in st.css files. 
Seems some values are missing [Here](https://github.com/wix/stylable/blob/master/packages/core/src/native-reserved-lists.ts#L155).

(See values - in [clip](https://developer.mozilla.org/en-US/docs/Web/CSS/clip)/[clip-path](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path))

**Comment by tomrav** [comment]
Resolved in #789.

**Comment by tomrav** [comment]
This is not yet published in `master`, but will be included in the next release.
