### ISSUE TITLE
webpack-extensions should declare webpack as a peerDependancy

### ISSUE THREAD

**Issue by NitayRabi** [wix/stylable#814]
Expected behaviour - 

Should declare webpack as peerDependancy, similar to [@stylable/webpack-plugin](https://github.com/wix/stylable/blob/master/packages/webpack-plugin/package.json#L15)

Actual behaviour - 

https://github.com/wix/stylable/blob/master/packages/webpack-extensions/package.json#L21

Declares webpack as dependancy, causing issues with mismatching versions (example, yoshi(@3) brings a [different version](https://github.com/wix/yoshi/blob/version_3.x/packages/yoshi/package.json#L116))

**Comment by AviVahl** [comment]
fixed in `master` (v2) and `1.x` (v1) branches. next release from each branch should include it.
