### ISSUE TITLE
-st-compose documentation need better examples

### ISSUE THREAD

**Issue by qballer** [wix/stylable#84]
[compose](https://github.com/wixplosives/stylable/blob/master/_docs/references/compose-css-class.md) example isn't clear in the sense what you are getting out of it. The css output isn't really helping here. We should see the service this operation provides.

cc: @barak007, @AnnieLR

**Comment by tomrav** [comment]
`-st-compose` has been deprecated.

**Comment by tomrav** [comment]
`-st-compose` has been deprecated.
