### ISSUE TITLE
Minimizer: unpredictable builds without chunk hash updating

### ISSUE THREAD

**Issue by dangreen** [wix/stylable#860]
3 builds of the same code:

1)
![Снимок экрана 2019-11-05 в 19 08 18](https://user-images.githubusercontent.com/986756/68206982-92232c00-0000-11ea-8cc7-974af950a008.png)

2) 
![Снимок экрана 2019-11-05 в 19 10 01](https://user-images.githubusercontent.com/986756/68207006-9f401b00-0000-11ea-9308-b02d9171040d.png)

3)
![Снимок экрана 2019-11-05 в 19 10 44](https://user-images.githubusercontent.com/986756/68207053-b2eb8180-0000-11ea-8938-a268f234d2cf.png)

Problems:
1) Why each build of the same code generates new class names?
2) Ok, it generates new class names, but why it didn't affect on chunk hashes? 
I tried `chunkhash` and `contenthash` - same results.

**Comment by tomrav** [comment]
1. We think it's related to the order in which webpack processes modules, and our optimizer isn't properly taking this into account.
2. Maybe the optimizer is being applied after webpack has calculated the chunk hash. We need to investigate. 

Can you please try to set `optimize: { shortNamespaces: false}` in your stylable webpack plugin config, it should be more consistent with namespaces. If you're also seeing classnames being inconsistent, you can try to disable `classNameOptimizations` as well. Does it affect the issue?

**Comment by dangreen** [comment]
@tomrav Yes, `shortNamespaces: false` is work good, but now I have long class names.

**Comment by dangreen** [comment]
@tomrav Today I had the new case:

 `shortNamespaces: false, classNameOptimizations: true`

a:
```
(window.__LOADABLE_LOADED_CHUNKS__ = window.__LOADABLE_LOADED_CHUNKS__ || []).push([[16], {
    FnI7: function(e, s, n) {
        e.exports = n.stylable.create("ProfileCard2978010291", {
            classes: {
                root: "s83",
                link: "s84",
                info: "s85",
                img: "s86",
                label: "s87",
                name: "s88",
                description: "s89",
                location: "s90",
                footer: "s91",
                contacts: "s92",
                contactLink: "s93",
                icon: "s94"
            },
            vars: {},
            stVars: {
                sizeInfo: "35em"
            },
            keyframes: {}
        }, "", 47, "FnI7", null)
    },
...
```

b:
```
(window.__LOADABLE_LOADED_CHUNKS__ = window.__LOADABLE_LOADED_CHUNKS__ || []).push([[16], {
    FnI7: function(e, s, n) {
        e.exports = n.stylable.create("ProfileCard2978010291", {
            classes: {
                root: "s80",
                link: "s81",
                info: "s82",
                img: "s83",
                label: "s84",
                name: "s85",
                description: "s86",
                location: "s87",
                footer: "s88",
                contacts: "s89",
                contactLink: "s90",
                icon: "s91"
            },
            vars: {},
            stVars: {
                sizeInfo: "35em"
            },
            keyframes: {}
        }, "", 47, "FnI7", null)
    },
...
```

`team.06fc2a1823.js` - hash is same in both cases

**Comment by idoros** [comment]
We believe in the latest integration that uses content hash instead of chunk hash. If this still happens then feel free to re-open.
