### ISSUE TITLE
resolveSelectorElements should expose nested elements

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#891]
At the moment our `resolveSelectorElements` method does not properly handle nested parts of a selector (native nested pseudo states come to mind, such as `:not()`).

It should expose a new field on its return value, `nested` with the relevant AST information for those nodes and not resolve it as part of the root level selector.

```css
.root:not(.x) {}
```

**Comment by idoros** [comment]
The elements/resolveSelectorElements currently does not support nested inferred selectors. To accommodate them, a breaking change to the data structure would be necessary. As a result, this method is likely to be deprecated and replaced by the new selectorAstResolveMap, which maps the transformed AST nodes to the inferred selectors.

While it's not yet part of the public API, we're open to exposing it should there be a demand.
