### ISSUE TITLE
Webpack file-loader 5.0.0 causes error when using url()

### ISSUE THREAD

**Issue by idoros** [wix/stylable#903]
Using `@stylable/webpack-plugin` with [new 5.0.0 version](https://github.com/webpack-contrib/file-loader/releases/tag/v5.0.0) of `file-loader` fails when using `url()`. 

The reason is that the `esModule` flag defaults to true, generating `export default` which `stylable-module-helpers:renderStaticCSS` fails to handle.

To avoid this (currently) the `esModule` option can be turned back to false

**Comment by AviVahl** [comment]
Fixed by v3.1.0
