### ISSUE TITLE
Custom Selectors Syntax + Docs

### ISSUE THREAD

**Issue by arnonkehat** [wix/stylable#91]
# Custom selectors

// ToDo: write docs
// https://tabatkins.github.io/specs/css-aliases/#custom-selectors
// polyfill custom selector + expose as pseudo element

### Container / recursive components

// tree node example

### Interface for non-Stylable

**Comment by tomrav** [comment]
Feature is implemented, see [docs here](https://stylable.io/docs/references/custom-selectors)
