### ISSUE TITLE
"Request textDocument/signatureHelp failed" pops up on syntactic errors

### ISSUE THREAD

**Issue by alisey** [wix/stylable#935]
I'm using Stylable Intelligence for VS Code, and every time I make a syntactic error in the `value` function, e.g. type `color: value(`, the problems panel pops up, obscuring the code I'm writing.

![image](https://user-images.githubusercontent.com/415252/72248384-b4888580-35ff-11ea-8f11-07ad8c79be8c.png)

It would be a better user experience to underline the error in red without opening the problems panel.

**Comment by tomrav** [comment]
This is a bug with our language server, such exceptions should not be thrown!

I'll take a look and see how straight forward this would be to fix quickly.

**Comment by AviVahl** [comment]
The errors suggest raw URIs (`file://`) are being passed to the file system calls.

**Comment by alisey** [comment]
I no longer get this error. Was the language server fixed or maybe updating deps fixed it at some point?

**Comment by tomrav** [comment]
We did release a new version of the extension, glad it resolves the issue. :)
