### ISSUE TITLE
Mixins don't get recompiled in webpack watch mode

### ISSUE THREAD

**Issue by alisey** [wix/stylable#937]
If in the following example I modify `fancy-border-mixin.st.css`, the changes are not recompiled.

```
:import {
  -st-from: './fancy-border-mixin.st.css';
  -st-default: FancyBorder;
}

.fancyButton {
  --st-mixin: FancyBorder;
}
```

**Comment by idoros** [comment]
Does changing something in the file that apply the mixin cause the change to be updated?

**Comment by alisey** [comment]
@idoros yes.

**Comment by tomrav** [comment]
This should now be resolved.
