### ISSUE TITLE
output clean namespace 

### ISSUE THREAD

**Issue by idoros** [wix/stylable#94]
At the moment any namespace is composed of `@namespace + file content hash`.

- [ ] add hash only in cases of conflict and we can use a simple counter instead of hash
- [x] use filename as default `@namespace`

In case of CSS standalone export we can generate better or configurable namespace, but its not in our short term goals.

**Comment by tomrav** [comment]
Resolved [here](https://github.com/wix/stylable/tree/master/packages/stylable-webpack-plugin)

**Comment by cristinallamas** [comment]
> Resolved [here](https://github.com/wix/stylable/tree/master/packages/stylable-webpack-plugin)

this is an empty link I'm afraid, where can I find this now?

**Comment by idoros** [comment]
I can't tell where the original comment used to linked, but namespace can be managed using [stylable.config](https://stylable.io/docs/getting-started/stylable-config#defaultconfig) and [resolveNamespace](https://stylable.io/docs/references/programmatic-api#resolvenamespace). Additionally, we have some helpers to configure namespace: `createNamespaceStrategyNode` from `@stylable/node` and `createNamespaceStrategy` from `@stylable/core`.
